insert into Rating (U_iD, D_iD, Score, Comments) values (74, 6, 2, 'Vivamus tortor.');
insert into Rating (U_iD, D_iD, Score, Comments) values (68, 14, 4, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into Rating (U_iD, D_iD, Score, Comments) values (60, 15, 4, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (95, 5, 4, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (96, 5, 5, 'Morbi a ipsum. Integer a nibh. In quis justo.');
insert into Rating (U_iD, D_iD, Score, Comments) values (50, 3, 3, 'Nullam varius.');
insert into Rating (U_iD, D_iD, Score, Comments) values (97, 3, 1, 'Nam tristique tortor eu pede.');
insert into Rating (U_iD, D_iD, Score, Comments) values (93, 7, 1, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into Rating (U_iD, D_iD, Score, Comments) values (54, 10, 5, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into Rating (U_iD, D_iD, Score, Comments) values (83, 15, 4, 'Etiam justo.');
insert into Rating (U_iD, D_iD, Score, Comments) values (75, 9, 5, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into Rating (U_iD, D_iD, Score, Comments) values (81, 14, 3, 'Aliquam non mauris. Morbi non lectus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (69, 5, 3, 'In blandit ultrices enim.');
insert into Rating (U_iD, D_iD, Score, Comments) values (39, 1, 3, 'In hac habitasse platea dictumst.');
insert into Rating (U_iD, D_iD, Score, Comments) values (25, 15, 5, 'Aliquam erat volutpat.');
insert into Rating (U_iD, D_iD, Score, Comments) values (83, 15, 4, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (30, 13, 3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (28, 15, 4, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into Rating (U_iD, D_iD, Score, Comments) values (44, 11, 1, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (87, 2, 5, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into Rating (U_iD, D_iD, Score, Comments) values (6, 3, 2, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
insert into Rating (U_iD, D_iD, Score, Comments) values (50, 5, 2, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into Rating (U_iD, D_iD, Score, Comments) values (9, 8, 1, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into Rating (U_iD, D_iD, Score, Comments) values (45, 5, 1, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (18, 8, 5, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into Rating (U_iD, D_iD, Score, Comments) values (25, 5, 2, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into Rating (U_iD, D_iD, Score, Comments) values (55, 5, 5, 'Donec semper sapien a libero.');
insert into Rating (U_iD, D_iD, Score, Comments) values (78, 10, 2, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into Rating (U_iD, D_iD, Score, Comments) values (70, 11, 3, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into Rating (U_iD, D_iD, Score, Comments) values (2, 3, 3, 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into Rating (U_iD, D_iD, Score, Comments) values (7, 5, 1, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into Rating (U_iD, D_iD, Score, Comments) values (84, 7, 5, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into Rating (U_iD, D_iD, Score, Comments) values (16, 2, 5, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (30, 10, 4, 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into Rating (U_iD, D_iD, Score, Comments) values (21, 7, 5, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into Rating (U_iD, D_iD, Score, Comments) values (56, 13, 5, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (86, 8, 3, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Rating (U_iD, D_iD, Score, Comments) values (55, 14, 1, 'Nunc purus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (36, 9, 1, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into Rating (U_iD, D_iD, Score, Comments) values (96, 8, 1, 'Aliquam non mauris. Morbi non lectus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (86, 2, 3, 'Nunc purus. Phasellus in felis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (23, 6, 5, 'Proin at turpis a pede posuere nonummy.');
insert into Rating (U_iD, D_iD, Score, Comments) values (75, 12, 3, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into Rating (U_iD, D_iD, Score, Comments) values (30, 4, 5, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (45, 2, 2, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (56, 11, 2, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into Rating (U_iD, D_iD, Score, Comments) values (50, 6, 4, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into Rating (U_iD, D_iD, Score, Comments) values (17, 7, 4, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Rating (U_iD, D_iD, Score, Comments) values (5, 7, 5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into Rating (U_iD, D_iD, Score, Comments) values (25, 7, 4, 'Integer non velit.');
insert into Rating (U_iD, D_iD, Score, Comments) values (47, 11, 2, 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into Rating (U_iD, D_iD, Score, Comments) values (73, 11, 4, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into Rating (U_iD, D_iD, Score, Comments) values (41, 11, 2, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.');
insert into Rating (U_iD, D_iD, Score, Comments) values (92, 4, 2, 'Curabitur gravida nisi at nibh.');
insert into Rating (U_iD, D_iD, Score, Comments) values (54, 3, 3, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into Rating (U_iD, D_iD, Score, Comments) values (100, 9, 4, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into Rating (U_iD, D_iD, Score, Comments) values (100, 1, 5, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into Rating (U_iD, D_iD, Score, Comments) values (56, 12, 2, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Rating (U_iD, D_iD, Score, Comments) values (55, 2, 4, 'Sed sagittis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (26, 12, 4, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into Rating (U_iD, D_iD, Score, Comments) values (20, 12, 1, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
insert into Rating (U_iD, D_iD, Score, Comments) values (97, 12, 1, 'In quis justo. Maecenas rhoncus aliquam lacus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (73, 9, 1, 'Nulla nisl. Nunc nisl.');
insert into Rating (U_iD, D_iD, Score, Comments) values (36, 1, 1, 'Aliquam erat volutpat. In congue.');
insert into Rating (U_iD, D_iD, Score, Comments) values (64, 12, 1, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into Rating (U_iD, D_iD, Score, Comments) values (63, 13, 2, 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (64, 2, 2, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into Rating (U_iD, D_iD, Score, Comments) values (85, 5, 2, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into Rating (U_iD, D_iD, Score, Comments) values (3, 12, 1, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into Rating (U_iD, D_iD, Score, Comments) values (5, 4, 1, 'Suspendisse potenti.');
insert into Rating (U_iD, D_iD, Score, Comments) values (14, 7, 3, 'Sed sagittis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (87, 4, 3, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.');
insert into Rating (U_iD, D_iD, Score, Comments) values (78, 12, 3, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into Rating (U_iD, D_iD, Score, Comments) values (56, 1, 2, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into Rating (U_iD, D_iD, Score, Comments) values (43, 7, 1, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Rating (U_iD, D_iD, Score, Comments) values (79, 12, 5, 'Donec semper sapien a libero.');
insert into Rating (U_iD, D_iD, Score, Comments) values (48, 7, 2, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into Rating (U_iD, D_iD, Score, Comments) values (55, 14, 1, 'Phasellus sit amet erat.');
insert into Rating (U_iD, D_iD, Score, Comments) values (24, 7, 2, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into Rating (U_iD, D_iD, Score, Comments) values (5, 10, 5, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (26, 11, 3, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into Rating (U_iD, D_iD, Score, Comments) values (38, 12, 4, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.');
insert into Rating (U_iD, D_iD, Score, Comments) values (81, 8, 5, 'In congue.');
insert into Rating (U_iD, D_iD, Score, Comments) values (21, 12, 3, 'Suspendisse potenti. In eleifend quam a odio.');
insert into Rating (U_iD, D_iD, Score, Comments) values (66, 10, 5, 'Donec semper sapien a libero. Nam dui.');
insert into Rating (U_iD, D_iD, Score, Comments) values (94, 12, 4, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into Rating (U_iD, D_iD, Score, Comments) values (35, 11, 1, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (20, 12, 4, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into Rating (U_iD, D_iD, Score, Comments) values (71, 10, 2, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into Rating (U_iD, D_iD, Score, Comments) values (40, 9, 5, 'Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into Rating (U_iD, D_iD, Score, Comments) values (49, 1, 4, 'In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into Rating (U_iD, D_iD, Score, Comments) values (45, 12, 1, 'Donec semper sapien a libero.');
insert into Rating (U_iD, D_iD, Score, Comments) values (36, 9, 3, 'Duis mattis egestas metus. Aenean fermentum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (55, 10, 2, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into Rating (U_iD, D_iD, Score, Comments) values (9, 6, 4, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (56, 13, 4, 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into Rating (U_iD, D_iD, Score, Comments) values (77, 3, 4, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (69, 8, 3, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into Rating (U_iD, D_iD, Score, Comments) values (18, 13, 4, 'Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into Rating (U_iD, D_iD, Score, Comments) values (83, 2, 2, 'Proin eu mi.');
insert into Rating (U_iD, D_iD, Score, Comments) values (100, 7, 3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into Rating (U_iD, D_iD, Score, Comments) values (57, 4, 1, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.');
insert into Rating (U_iD, D_iD, Score, Comments) values (46, 12, 5, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (8, 3, 5, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (91, 2, 4, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into Rating (U_iD, D_iD, Score, Comments) values (28, 11, 3, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into Rating (U_iD, D_iD, Score, Comments) values (10, 5, 5, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into Rating (U_iD, D_iD, Score, Comments) values (71, 10, 5, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (58, 1, 5, 'Etiam pretium iaculis justo.');
insert into Rating (U_iD, D_iD, Score, Comments) values (42, 1, 4, 'Morbi a ipsum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (69, 9, 5, 'Nulla ut erat id mauris vulputate elementum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (41, 4, 3, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (92, 11, 1, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (26, 3, 5, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into Rating (U_iD, D_iD, Score, Comments) values (8, 3, 5, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Rating (U_iD, D_iD, Score, Comments) values (42, 1, 3, 'Morbi non quam nec dui luctus rutrum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (57, 1, 2, 'Praesent blandit lacinia erat.');
insert into Rating (U_iD, D_iD, Score, Comments) values (69, 15, 2, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (97, 13, 2, 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into Rating (U_iD, D_iD, Score, Comments) values (81, 14, 4, 'Sed ante.');
insert into Rating (U_iD, D_iD, Score, Comments) values (91, 6, 5, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.');
insert into Rating (U_iD, D_iD, Score, Comments) values (49, 2, 4, 'Duis mattis egestas metus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (27, 5, 3, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (18, 9, 1, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into Rating (U_iD, D_iD, Score, Comments) values (64, 11, 1, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into Rating (U_iD, D_iD, Score, Comments) values (12, 4, 1, 'Integer non velit.');
insert into Rating (U_iD, D_iD, Score, Comments) values (6, 15, 3, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Rating (U_iD, D_iD, Score, Comments) values (16, 3, 1, 'Donec quis orci eget orci vehicula condimentum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (89, 9, 1, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (54, 6, 2, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (9, 11, 4, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (39, 7, 3, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (13, 4, 1, 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into Rating (U_iD, D_iD, Score, Comments) values (81, 1, 3, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into Rating (U_iD, D_iD, Score, Comments) values (52, 15, 3, 'Aenean sit amet justo. Morbi ut odio.');
insert into Rating (U_iD, D_iD, Score, Comments) values (31, 8, 2, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (13, 12, 2, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (80, 5, 2, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Rating (U_iD, D_iD, Score, Comments) values (3, 4, 2, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into Rating (U_iD, D_iD, Score, Comments) values (42, 7, 2, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into Rating (U_iD, D_iD, Score, Comments) values (92, 10, 2, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (92, 15, 3, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into Rating (U_iD, D_iD, Score, Comments) values (2, 1, 4, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into Rating (U_iD, D_iD, Score, Comments) values (66, 5, 2, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
insert into Rating (U_iD, D_iD, Score, Comments) values (24, 5, 3, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into Rating (U_iD, D_iD, Score, Comments) values (37, 4, 2, 'Cras pellentesque volutpat dui.');
insert into Rating (U_iD, D_iD, Score, Comments) values (90, 9, 3, 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into Rating (U_iD, D_iD, Score, Comments) values (62, 13, 1, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into Rating (U_iD, D_iD, Score, Comments) values (94, 3, 1, 'Suspendisse potenti. In eleifend quam a odio.');
insert into Rating (U_iD, D_iD, Score, Comments) values (91, 1, 3, 'Nulla tellus.');
